// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.2
// source: blog/blogpb/blog.proto

package blogpb

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BlogServicClient is the client API for BlogServic service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlogServicClient interface {
}

type blogServicClient struct {
	cc grpc.ClientConnInterface
}

func NewBlogServicClient(cc grpc.ClientConnInterface) BlogServicClient {
	return &blogServicClient{cc}
}

// BlogServicServer is the server API for BlogServic service.
// All implementations must embed UnimplementedBlogServicServer
// for forward compatibility
type BlogServicServer interface {
	mustEmbedUnimplementedBlogServicServer()
}

// UnimplementedBlogServicServer must be embedded to have forward compatible implementations.
type UnimplementedBlogServicServer struct {
}

func (UnimplementedBlogServicServer) mustEmbedUnimplementedBlogServicServer() {}

// UnsafeBlogServicServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlogServicServer will
// result in compilation errors.
type UnsafeBlogServicServer interface {
	mustEmbedUnimplementedBlogServicServer()
}

func RegisterBlogServicServer(s grpc.ServiceRegistrar, srv BlogServicServer) {
	s.RegisterService(&BlogServic_ServiceDesc, srv)
}

// BlogServic_ServiceDesc is the grpc.ServiceDesc for BlogServic service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlogServic_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blog.BlogServic",
	HandlerType: (*BlogServicServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "blog/blogpb/blog.proto",
}
